// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXeC-Eb1hojO_JLVK-EtX7Ec7Wiaq5W1Y',
    appId: '1:750036310975:web:4f724c7c672c7f939f1f0a',
    messagingSenderId: '750036310975',
    projectId: 'helpdesk-app-44446',
    authDomain: 'helpdesk-app-44446.firebaseapp.com',
    storageBucket: 'helpdesk-app-44446.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSTFEm6VOcnMRVcuN72NzkO8PzZPHiRUk',
    appId: '1:750036310975:android:d64786e3e21115c59f1f0a',
    messagingSenderId: '750036310975',
    projectId: 'helpdesk-app-44446',
    storageBucket: 'helpdesk-app-44446.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcD67QmH9oZvIzaNjT__cppMmvyNNC6rY',
    appId: '1:750036310975:ios:9162601e63937de39f1f0a',
    messagingSenderId: '750036310975',
    projectId: 'helpdesk-app-44446',
    storageBucket: 'helpdesk-app-44446.appspot.com',
    iosBundleId: 'com.example.helpdeskApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcD67QmH9oZvIzaNjT__cppMmvyNNC6rY',
    appId: '1:750036310975:ios:9162601e63937de39f1f0a',
    messagingSenderId: '750036310975',
    projectId: 'helpdesk-app-44446',
    storageBucket: 'helpdesk-app-44446.appspot.com',
    iosBundleId: 'com.example.helpdeskApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXeC-Eb1hojO_JLVK-EtX7Ec7Wiaq5W1Y',
    appId: '1:750036310975:web:a62c9f9e9b956fbd9f1f0a',
    messagingSenderId: '750036310975',
    projectId: 'helpdesk-app-44446',
    authDomain: 'helpdesk-app-44446.firebaseapp.com',
    storageBucket: 'helpdesk-app-44446.appspot.com',
  );
}
